companies = [
"kellogg co.",
"ihs markit ltd.",
"tripadvisor",
"toray industries",
"advantest",
"principal financial group",
"kimberly-clark",
"citrix systems",
"asahi glass",
"dainippon screen",
"salesforce.com",
"baxter international inc.",
"netapp",
"johnson controls international",
"fidelity national information services",
"fifth third bancorp",
"discovery inc. class a",
"varian medical systems",
"tokyo gas",
"concho resources",
"facebook",
"maxim integrated products inc",
"t.co",
"ajinomoto",
"hilton worldwide holdings inc",
"keysight technologies",
"charles schwab corporation",
"nissan motor",
"isuzu motors",
"konica minolta holdings",
"seiko epson",
"groupon",
"royal caribbean cruises ltd",
"carnival corp.",
"keisei electric railway",
"arthur j. gallagher & co.",
"d. r. horton",
"tokio marine holdings",
"intl flavors & fragrances",
"pentair plc",
"american airlines group",
"kobe steel",
"unitedhealth group",
"suzuki motor",
"intel corp.",
"stanley black & decker",
"pfizer",
"sumitomo heavy industries",
"naver",
"goldman sachs",
"kyocera",
"flir systems",
"expeditors",
"coty, inc",
"news corp. class b",
"jingdong mall",
"costco wholesale corp.",
"applied materials inc.",
"bloomberg l.p.",
"borgwarner",
"equity residential",
"maruha nichiro holdings",
"mizuho financial group",
"ameren corp",
"cme group inc.",
"facebook, inc.",
"intuit inc. ",
"leggett & platt",
"medtronic plc",
"cadence design systems",
"pnc financial services",
"visa inc.",
"discover financial services",
"mondelez international",
"fuji electric holdings",
"vk",
"bristol-myers squibb",
"mcdonald's",
"westrock",
"haseko corp.",
"tokyu",
"cardinal health inc.",
"secom",
"henry schein",
"windows live",
"lilly (eli) & co.",
"aliexpress",
"emerson electric company",
"public storage",
"mattel inc.",
"symantec corp.",
"oneok",
"google hong kong",
"hess corporation",
"sealed air",
"capri holdings",
"wellcare",
"alphabet inc class a",
"huntington ingalls industries",
"general electric",
"l brands inc.",
"takeda pharmaceutical company",
"ansys",
"paypal",
"cabot oil & gas",
"odakyu electric railway",
"dowdupont",
"nec",
"lam research",
"weyerhaeuser",
"avery dennison corp",
"sl green realty",
"twenty-first century fox class b",
"ameriprise financial",
"mylan n.v.",
"snap-on",
"delta air lines inc.",
"booking holdings inc",
"intuitive surgical inc.",
"spotify",
"vertex pharmaceuticals inc",
"toho zinc",
"united continental holdings",
"merck & co.",
"blackrock",
"lennar corp.",
"agilent technologies inc",
"alliant energy corp",
"yamaha motor",
"paccar inc.",
"fujifilm holdings",
"kajima",
"toyota tsusho",
"lowe's cos.",
"kikkoman",
"pornhub",
"matsui securities",
"danaher corp.",
"nielsen holdings",
"resona holdings",
"svb financial",
"s&p global, inc.",
"monster beverage",
"davita inc.",
"textron inc.",
"nitto denko",
"home depot",
"corning inc.",
"tyson foods",
"nextera energy",
"grainger (w.w.) inc.",
"ametek inc.",
"discovery inc. class c",
"amada co. ltd. ",
"shin-etsu chemical",
"seven & i holdings",
"thermo fisher scientific",
"international business machines",
"united rentals, inc.",
"denso",
"tokyo electron",
"j. front retailing",
"willis towers watson",
"chugai pharmaceutical",
"laboratory corp. of america holding",
"duke energy",
"valero energy",
"google germany",
"nippon paper group, inc.",
"concordia financial group",
"dover corp.",
"sky perfect jsat holdings inc.",
"skyworks solutions",
"anthem inc.",
"cboe global markets",
"hino motors",
"centerpoint energy",
"analog devices, inc.",
"simon property group inc",
"fanuc",
"wabtec corporation",
"honda motor",
"republic services inc",
"fastenal co",
"itochu",
"edison int'l",
"wells fargo",
"hitachi",
"google france",
"consolidated edison",
"charter communications",
"nvidia corporation",
"union pacific",
"pepsico inc.",
"casio computer",
"walmart",
"cognizant technology solutions",
"kubota",
"sumitomo",
"digital realty trust inc",
"illinois tool works",
"walgreens boots alliance",
"waste management inc.",
"msci inc",
"toyo seikan kaisha",
"isetan mitsukoshi holdings",
"v.f. corp.",
"lkq corporation",
"amazon.com inc.",
"paychex inc.",
"cisco systems",
"kroger co.",
"oji paper",
"t. rowe price group",
"komatsu",
"sekisui house",
"cvs health",
"mitsui mining & smelting",
"molson coors brewing company",
"assurant",
"chevron",
"furukawa electric",
"lockheed martin corp.",
"mitsui engineering & shipbuilding",
"mitsubishi ufj financial group",
"raytheon co.",
"automatic data processing",
"gs yuasa",
"netflix",
"csx corp.",
"jacobs engineering group",
"uber",
"regeneron",
"furukawa",
"nippon steel",
"american international group",
"martin marietta materials",
"phillips 66",
"tencent",
"everest re group ltd.",
"daikin industries",
"polo ralph lauren corp.",
"yahoo! japan",
"realty income corporation",
"canon",
"airbnb",
"tokai carbon",
"tokyo electric power",
"jxtg holdings",
"sumco",
"amazon",
"fortune brands home & security",
"entergy corp.",
"ebay",
"synchrony financial",
"global payments inc.",
"noble energy inc",
"sumitomo chemical",
"alps electric",
"yahoo japan",
"a.o. smith corp",
"affiliated managers group inc",
"resmed",
"arconic inc.",
"mgm resorts international",
"nsk",
"shionogi",
"dish network",
"amp project",
"perrigo",
"hcp inc.",
"twenty-first century fox class a",
"fluor corp.",
"general motors",
"dowa holdings",
"tosoh",
"j. b. hunt transport services",
"the travelers companies inc.",
"mitsui o.s.k. lines",
"nippon meat packers",
"dte energy co.",
"sempra energy",
"instagram",
"ntn",
"caterpillar",
"goldman sachs group",
"workday",
"evergy",
"dai nippon printing",
"metlife inc.",
"becton dickinson",
"flipkart",
"amgen inc.",
"familymart uny holdings",
"pioneer natural resources",
"toto ltd.",
"intercontinental exchange",
"chubu electric power",
"the home depot",
"tokyo dome",
"livejasmin",
"abbott laboratories",
"showa denko",
"toho",
"haosou",
"ppg industries",
"aes corp",
"sumitomo mitsui financial group",
"hca holdings",
"exxon mobil corp.",
"microsoft office",
"unitika",
"american electric power",
"northrop grumman corp.",
"kyowa hakko kirin",
"sumitomo dainippon pharma",
"minebea",
"eastman chemical",
"pinnacle west capital",
"verisk analytics",
"github",
"fortinet",
"deere & co.",
"humana inc.",
"ebay inc.",
"honeywell int'l inc.",
"shinsei bank",
"verizon",
"kddi",
"sumitomo metal mining",
"hasbro inc.",
"american express co",
"hollyfrontier corp",
"xcel energy inc",
"carmax inc",
"credit saison",
"yahoo!",
"terumo",
"nektar therapeutics",
"advance auto parts",
"jm smucker",
"public serv. enterprise inc.",
"linde plc",
"sherwin-williams",
"united parcel service",
"united health group inc.",
"mettler toledo",
"united technologies",
"t&d holdings",
"target corp.",
"hp inc.",
"ebara",
"nrg energy",
"marui group",
"inpex",
"denki kagaku kogyo",
"zoetis",
"mitsubishi estate",
"te connectivity ltd.",
"nichirei",
"boeing company",
"lamb weston holdings inc",
"kirin brewery",
"chiyoda",
"all nippon airways",
"helmerich & payne",
"sumitomo mitsui trust holdings",
"air products & chemicals inc",
"f5 networks",
"sojitz",
"whirlpool corp.",
"alphabet inc.",
"marubeni",
"campbell soup",
"microsoft corp.",
"xnxx",
"ms&ad insurance group",
"transdigm group",
"fortive corp",
"nissan chemical industries",
"google brazil",
"wynn resorts ltd",
"o'reilly automotive",
"garmin ltd.",
"iqvia holdings inc.",
"take-two interactive",
"eisai",
"google",
"meituan-dianping",
"3m",
"meiji holdings",
"berkshire hathaway",
"bank of america corp",
"copart inc",
"taiheiyo cement",
"ngk insulators",
"parker-hannifin",
"aptiv plc",
"yamato holdings",
"baidu",
"l-3 communications holdings",
"caterpillar inc.",
"halliburton co.",
"cbre group",
"procter & gamble",
"ford motor",
"taiyo yuden",
"unum group",
"mccormick & co.",
"sumitomo osaka cement",
"shenma",
"waters corporation",
"the cooper companies",
"booking",
"mitsubishi motors",
"aeon",
"odnoklassniki",
"host hotels & resorts",
"morgan stanley",
"eog resources",
"microchip technology",
"verizon communications",
"astellas pharma",
"oki electric industry",
"adobe systems inc",
"ipg photonics corp.",
"nippon express",
"cms energy",
"nikon",
"mitsubishi",
"netflix inc.",
"general mills",
"perkinelmer",
"google india",
"stack overflow",
"atmos energy corp",
"porn555",
"japan tobacco",
"pfizer inc.",
"xylem inc.",
"youtube",
"marathon oil corp.",
"nippon suisan kaisha",
"wikipedia",
"southern co.",
"norwegian cruise line",
"cintas corporation",
"viacom inc.",
"sina weibo",
"welltower inc.",
"visa",
"e*trade",
"expedia group",
"suntrust banks",
"arista networks",
"yamaha",
"sony financial",
"linkedin",
"xhamster",
"obayashi",
"activision blizzard",
"citizens financial group",
"american tower corp.",
"dollar tree",
"3m company",
"avalonbay communities, inc.",
"panasonic",
"equifax inc.",
"conocophillips",
"technipfmc",
"microsoft",
"hitachi zōsen",
"cf industries holdings inc",
"gartner inc",
"qorvo",
"advanced micro devices inc",
"micron technology",
"lyondellbasell",
"nike",
"regency centers corporation",
"gap inc.",
"mastercard inc.",
"quest diagnostics",
"sogou",
"flowserve corporation",
"edwards lifesciences",
"rollins inc.",
"red hat inc.",
"mitsubishi materials",
"dxc technology",
"autodesk inc.",
"sapporo holdings",
"jefferies financial group",
"fedex corporation",
"fukuoka financial group",
"jtekt",
"citigroup inc.",
"first republic bank",
"kansas city southern",
"kawasaki heavy industries",
"sina corp",
"gilead sciences",
"nippon kayaku",
"okuma holdings",
"genuine parts",
"estee lauder cos.",
"edreams odigeo",
"juniper networks",
"jpmorgan chase & co.",
"nisshinbo holdings",
"albemarle corp",
"ntt docomo",
"jack henry & associates inc",
"stryker corp.",
"tractor supply company",
"xerox",
"mazda motor",
"mohawk industries",
"imdb",
"starbucks corp.",
"kohl's corp.",
"sumitomo electric industries",
"essex property trust, inc.",
"newell brands",
"diamondback energy",
"aon plc",
"pulte homes inc.",
"franklin resources",
"zions bancorp",
"williams cos.",
"hitachi construction machinery",
"jgc corporation",
"accuweather",
"xilinx",
"ulta beauty",
"harris corporation",
"asahi breweries",
"b2w",
"ibm",
"block h&r",
"nippon electric glass",
"apache corporation",
"google spain",
"google italy",
"schlumberger ltd.",
"samsung",
"biogen inc.",
"nordstrom",
"kraft heinz co",
"nippon sheet glass",
"western union co",
"travelers",
"walt disney",
"southwest airlines",
"toppan printing",
"trend micro",
"apartment investment & management ",
"the bank of new york mellon corp.",
"jpmorgan chase",
"freeport-mcmoran inc.",
"constellation brands",
"citizen holdings",
"comerica inc.",
"nippon yusen",
"northern trust corp.",
"idexx laboratories",
"pioneer",
"otsuka holdings co.",
"mitsui",
"brighthouse financial inc",
"mcdonald's corp.",
"nasdaq, inc.",
"nisshin seifun group",
"cincinnati financial",
"coca-cola company",
"kuraray",
"sysco corp.",
"intel",
"robert half international",
"softbank",
"brown-forman corp.",
"fleetcor technologies inc",
"mitsui chemicals",
"mitsui fudosan",
"boeing",
"jfe holdings",
"bitly",
"pvh corp.",
"konami",
"toyobo",
"duke realty corp",
"mckesson corp.",
"exelon corp.",
"dentsu",
"alaska air group inc",
"torchmark corp.",
"allegion",
"centene corporation",
"nisshin steel",
"the clorox company",
"interpublic group",
"broadridge financial solutions",
"american express",
"quanta services inc.",
"comcast corp.",
"exxonmobil",
"fujitsu",
"shizuoka bank",
"allstate corp",
"nomura holdings",
"apple",
"hewlett packard enterprise",
"alphabet inc class c",
"takara holdings",
"yandex",
"tencent qq",
"bridgestone",
"ecolab inc.",
"boston properties",
"electronic arts",
"aozora bank",
"east japan railway company",
"udr inc",
"invesco ltd.",
"osaka gas",
"total system services",
"illumina inc",
"dai-ichi life",
"tiffany & co.",
"national oilwell varco inc.",
"regions financial corp.",
"incyte",
"ihi",
"alipay",
"fiserv inc",
"ingersoll-rand plc",
"tokuyama corporation",
"marathon petroleum",
"ball corp",
"boston scientific",
"roper technologies",
"progressive corp.",
"cbs corp.",
"pinterest",
"loews corp.",
"state street corp.",
"iron mountain incorporated",
"showa shell sekiyu",
"twitter, inc.",
"mitsubishi heavy industries",
"west japan railway",
"taobao",
"reddit",
"bing",
"texas instruments",
"amazon japan",
"hanesbrands inc",
"under armour class a",
"yum! brands inc",
"amerisourcebergen corp",
"at&t inc.",
"teijin",
"asahi kasei",
"daiwa house industry",
"chevron corp.",
"eaton corporation",
"cummins inc.",
"the mosaic company",
"tmall",
"olympus",
"takashimaya",
"whatsapp",
"moody's corp",
"rakuten",
"news corp. class a",
"dentsply sirona",
"google japan",
"newmont mining corporation",
"american water works company inc",
"asos.com",
"sompo holdings",
"kansai electric power",
"dena",
"celgene corp.",
"broadcom",
"harley-davidson",
"zimmer biomet holdings",
"people's united financial",
"anadarko petroleum corp",
"twitch",
"extra space storage",
"tapestry, inc.",
"baker hughes, a ge company",
"apple inc.",
"archer-daniels-midland co",
"alexion pharmaceuticals",
"m&t bank corp.",
"sohu",
"abbvie inc.",
"raymond james financial inc.",
"cigna corp.",
"darden restaurants",
"western digital",
"kawasaki kisen kaisha",
"hartford financial svc.gp.",
"vornado realty trust",
"equinix",
"yokogawa electric",
"fast retailing",
"align technology",
"dominion energy",
"tdk",
"mail.ru",
"mid-america apartments",
"macerich",
"shiseido",
"kimco realty",
"chubb limited",
"daiichi sankyo",
"tokyo tatemono",
"keio",
"japan post holdings",
"sba communications",
"norfolk southern corp.",
"nucor corp.",
"mitsubishi logistics",
"ross stores",
"ube industries",
"coca-cola",
"international paper",
"ntt data",
"mitsubishi chemical holdings",
"yokohama rubber",
"universal health services, inc.",
"colgate-palmolive",
"quora",
"fujikura",
"abiomed inc",
"prologis",
"ricoh",
"autozone inc",
"rockwell automation inc.",
"msn",
"celanese corp.",
"qualcomm inc.",
"verisign inc.",
"blogspot",
"prudential financial",
"fmc corporation",
"eversource energy",
"xvideos",
"capital one financial",
"yaskawa electric corporation",
"google turkey",
"general dynamics",
"subaru",
"bb&t corporation",
"synopsys inc.",
"twitter",
"kao corp.",
"google uk",
"japan steel works",
"chiba bank",
"recruit holdings",
"oracle corp.",
"the walt disney company",
"packaging corporation of america",
"cimarex energy",
"merck & company",
"lincoln national",
"hologic",
"akamai technologies inc",
"netease",
"google russia",
"daiwa securities group",
"federal realty investment trust",
"jd.com",
"dollar general",
"allergan, plc",
"hormel foods corp.",
"tjx companies inc.",
"comsys holdings",
"mitsubishi electric",
"foot locker inc",
"sony",
"church & dwight",
"crown castle international corp.",
"conagra brands",
"tobu railway",
"devon energy",
"the hershey company",
"mail.ru",
"accenture plc",
"masco corp.",
"teleflex inc",
"u.s. bancorp",
"taisei",
"marsh & mclennan",
"aflac inc",
"alliance data systems",
"firstenergy corp",
"wec energy group inc",
"sumitomo realty & development",
"shimizu",
"johnson & johnson",
"motorola solutions inc.",
"vulcan materials",
"ppl corp.",
"alibaba",
"philip morris international",
"nisource inc.",
"keycorp",
"expedia",
"kla-tencor corp.",
"c. h. robinson worldwide",
"macy's inc.",
"best buy co. inc.",
"toyota motor",
"zalando",
"seagate technology",
"nippon light metal",
"cerner",
"occidental petroleum",
"tokyu land",
"altria group inc",
"csdn",
"amphenol corp",
"alexandria real estate equities",
"huntington bancshares",
"pacific metals",
"under armour class c",
"nippon telegraph and telephone",
"ventas inc",
"kinder morgan",
"chipotle mexican grill",
"omnicom group",
"central japan railway company",
"marriott int'l.",
"centurylink inc"
]