companies = [
"kellogg",
"ihs markit .",
"tripadvisor",
"toray industries",
"advantest",
"principal financial",
"kimberly-clark",
"citrix systems",
"asahi glass",
"dainippon screen",
"salesforce.com",
"baxter international",
"netapp",
"johnson controls international",
"fidelity national information services",
"fifth third bancorp",
"discovery class a",
"varian medical systems",
"tokyo gas",
"concho resources",
"facebook",
"maxim integrated products",
"t.",
"ajinomoto",
"hilton worldwide holdings",
"keysight technologies",
"charles schwab",
"nissan motor",
"isuzu motors",
"konica minolta holdings",
"seiko epson",
"groupon",
"royal caribbean cruises",
"carnival",
"keisei electric railway",
"arthur j. gallagher &",
"d. r. horton",
"tokio marine holdings",
"intl flavors & fragrances",
"pentair plc",
"american airlines",
"kobe steel",
"unitedhealth",
"suzuki motor",
"intel",
"stanley black & decker",
"pfizer",
"sumitomo heavy industries",
"naver",
"goldman sachs",
"kyocera",
"flir systems",
"expeditors",
"coty,",
"news class b",
"jingdong mall",
"costco wholesale",
"applied materials",
"bloomberg l.p.",
"borgwarner",
"equity residential",
"maruha nichiro holdings",
"mizuho financial",
"ameren",
"cme",
"facebook,",
"intuit",
"leggett & platt",
"medtronic plc",
"cadence design systems",
"pnc financial services",
"visa",
"discover financial services",
"mondelez international",
"fuji electric holdings",
"vk",
"bristol-myers squibb",
"mcdonald's",
"westrock",
"haseko",
"tokyu",
"cardinal health",
"secom",
"henry schein",
"windows live",
"lilly (eli) &",
"aliexpress",
"emerson electric",
"public storage",
"mattel",
"symantec",
"oneok",
"google hong kong",
"hess",
"sealed air",
"capri holdings",
"wellcare",
"alphabet class a",
"huntington ingalls industries",
"general electric",
"l brands",
"takeda pharmaceutical",
"ansys",
"paypal",
"cabot oil & gas",
"odakyu electric railway",
"dowdupont",
"nec",
"lam research",
"weyerhaeuser",
"avery dennison",
"sl green realty",
"twenty-first century fox class b",
"ameriprise financial",
"mylan n.v.",
"snap-on",
"delta air lines",
"booking holdings",
"intuitive surgical",
"spotify",
"vertex pharmaceuticals",
"toho zinc",
"united continental holdings",
"merck &",
"blackrock",
"lennar",
"agilent technologies",
"alliant energy",
"yamaha motor",
"paccar",
"fujifilm holdings",
"kajima",
"toyota tsusho",
"lowe's cos.",
"kikkoman",
"pornhub",
"matsui securities",
"danaher",
"nielsen holdings",
"resona holdings",
"svb financial",
"s&p global,",
"monster beverage",
"davita",
"textron",
"nitto denko",
"home depot",
"corning",
"tyson foods",
"nextera energy",
"grainger (w.w.)",
"ametek",
"discovery class c",
"amada .",
"shin-etsu chemical",
"seven & i holdings",
"thermo fisher scientific",
"international business machines",
"united rentals,",
"denso",
"tokyo electron",
"j. front retailing",
"willis towers watson",
"chugai pharmaceutical",
"laboratory of america holding",
"duke energy",
"valero energy",
"google germany",
"nippon paper ,",
"concordia financial",
"dover",
"sky perfect jsat holdings",
"skyworks solutions",
"anthem",
"cboe global markets",
"hino motors",
"centerpoint energy",
"analog devices,",
"simon property",
"fanuc",
"wabtec",
"honda motor",
"republic services",
"fastenal",
"itochu",
"edison int'l",
"wells fargo",
"hitachi",
"google france",
"consolidated edison",
"charter communications",
"nvidia",
"union pacific",
"pepsico",
"casio computer",
"walmart",
"cognizant technology solutions",
"kubota",
"sumitomo",
"digital realty trust",
"illinois tool works",
"walgreens boots alliance",
"waste management",
"msci",
"toyo seikan kaisha",
"isetan mitsukoshi holdings",
"v.f.",
"lkq",
"amazon.com",
"paychex",
"cisco systems",
"kroger",
"oji paper",
"t. rowe price",
"komatsu",
"sekisui house",
"cvs health",
"mitsui mining & smelting",
"molson coors brewing",
"assurant",
"chevron",
"furukawa electric",
"lockheed martin",
"mitsui engineering & shipbuilding",
"mitsubishi ufj financial",
"raytheon",
"automatic data processing",
"gs yuasa",
"netflix",
"csx",
"jacobs engineering",
"uber",
"regeneron",
"furukawa",
"nippon steel",
"american international",
"martin marietta materials",
"phillips 66",
"tencent",
"everest re .",
"daikin industries",
"polo ralph lauren",
"yahoo! japan",
"realty income",
"canon",
"airbnb",
"tokai carbon",
"tokyo electric power",
"jxtg holdings",
"sumco",
"amazon",
"fortune brands home & security",
"entergy",
"ebay",
"synchrony financial",
"global payments",
"noble energy",
"sumitomo chemical",
"alps electric",
"yahoo japan",
"a.o. smith",
"affiliated managers",
"resmed",
"arconic",
"mgm resorts international",
"nsk",
"shionogi",
"dish network",
"amp project",
"perrigo",
"hcp",
"twenty-first century fox class a",
"fluor",
"general motors",
"dowa holdings",
"tosoh",
"j. b. hunt transport services",
"the travelers companies",
"mitsui o.s.k. lines",
"nippon meat packers",
"dte energy",
"sempra energy",
"instagram",
"ntn",
"caterpillar",
"goldman sachs",
"workday",
"evergy",
"dai nippon printing",
"metlife",
"becton dickinson",
"flipkart",
"amgen",
"familymart uny holdings",
"pioneer natural resources",
"toto .",
"intercontinental exchange",
"chubu electric power",
"the home depot",
"tokyo dome",
"livejasmin",
"abbott laboratories",
"showa denko",
"toho",
"haosou",
"ppg industries",
"aes",
"sumitomo mitsui financial",
"hca holdings",
"exxon mobil",
"microsoft office",
"unitika",
"american electric power",
"northrop grumman",
"kyowa hakko kirin",
"sumitomo dainippon pharma",
"minebea",
"eastman chemical",
"pinnacle west capital",
"verisk analytics",
"github",
"fortinet",
"deere &",
"humana",
"ebay",
"honeywell int'l",
"shinsei bank",
"verizon",
"kddi",
"sumitomo metal mining",
"hasbro",
"american express",
"hollyfrontier",
"xcel energy",
"carmax",
"credit saison",
"yahoo!",
"terumo",
"nektar therapeutics",
"advance auto parts",
"jm smucker",
"public serv. enterprise",
"linde plc",
"sherwin-williams",
"united parcel service",
"united health",
"mettler toledo",
"united technologies",
"t&d holdings",
"target",
"hp",
"ebara",
"nrg energy",
"marui",
"inpex",
"denki kagaku kogyo",
"zoetis",
"mitsubishi estate",
"te connectivity .",
"nichirei",
"boeing",
"lamb weston holdings",
"kirin brewery",
"chiyoda",
"all nippon airways",
"helmerich & payne",
"sumitomo mitsui trust holdings",
"air products & chemicals",
"f5 networks",
"sojitz",
"whirlpool",
"alphabet",
"marubeni",
"campbell soup",
"microsoft",
"xnxx",
"ms&ad insurance",
"transdigm",
"fortive",
"nissan chemical industries",
"google brazil",
"wynn resorts",
"o'reilly automotive",
"garmin .",
"iqvia holdings",
"take-two interactive",
"eisai",
"google",
"meituan-dianping",
"3m",
"meiji holdings",
"berkshire hathaway",
"bank of america",
"copart",
"taiheiyo cement",
"ngk insulators",
"parker-hannifin",
"aptiv plc",
"yamato holdings",
"baidu",
"l-3 communications holdings",
"caterpillar",
"halliburton",
"cbre",
"procter & gamble",
"ford motor",
"taiyo yuden",
"unum",
"mccormick &",
"sumitomo osaka cement",
"shenma",
"waters",
"the cooper companies",
"booking",
"mitsubishi motors",
"aeon",
"odnoklassniki",
"host hotels & resorts",
"morgan stanley",
"eog resources",
"microchip technology",
"verizon communications",
"astellas pharma",
"oki electric industry",
"adobe systems",
"ipg photonics",
"nippon express",
"cms energy",
"nikon",
"mitsubishi",
"netflix",
"general mills",
"perkinelmer",
"google india",
"stack overflow",
"atmos energy",
"porn555",
"japan tobacco",
"pfizer",
"xylem",
"youtube",
"marathon oil",
"nippon suisan kaisha",
"wikipedia",
"southern",
"norwegian cruise line",
"cintas",
"viacom",
"sina weibo",
"welltower",
"visa",
"e*trade",
"expedia",
"suntrust banks",
"arista networks",
"yamaha",
"sony financial",
"linkedin",
"xhamster",
"obayashi",
"activision blizzard",
"citizens financial",
"american tower",
"dollar tree",
"3m",
"avalonbay communities,",
"panasonic",
"equifax",
"conocophillips",
"technipfmc",
"microsoft",
"hitachi zōsen",
"cf industries holdings",
"gartner",
"qorvo",
"advanced micro devices",
"micron technology",
"lyondellbasell",
"nike",
"regency centers",
"gap",
"mastercard",
"quest diagnostics",
"sogou",
"flowserve",
"edwards lifesciences",
"rollins",
"red hat",
"mitsubishi materials",
"dxc technology",
"autodesk",
"sapporo holdings",
"jefferies financial",
"fedex",
"fukuoka financial",
"jtekt",
"citigroup",
"first republic bank",
"kansas city southern",
"kawasaki heavy industries",
"sina",
"gilead sciences",
"nippon kayaku",
"okuma holdings",
"genuine parts",
"estee lauder cos.",
"edreams odigeo",
"juniper networks",
"jpmorgan chase &",
"nisshinbo holdings",
"albemarle",
"ntt docomo",
"jack henry & associates",
"stryker",
"tractor supply",
"xerox",
"mazda motor",
"mohawk industries",
"imdb",
"starbucks",
"kohl's",
"sumitomo electric industries",
"essex property trust,",
"newell brands",
"diamondback energy",
"aon plc",
"pulte homes",
"franklin resources",
"zions bancorp",
"williams cos.",
"hitachi construction machinery",
"jgc",
"accuweather",
"xilinx",
"ulta beauty",
"harris",
"asahi breweries",
"b2w",
"ibm",
"block h&r",
"nippon electric glass",
"apache",
"google spain",
"google italy",
"schlumberger .",
"samsung",
"biogen",
"nordstrom",
"kraft heinz",
"nippon sheet glass",
"western union",
"travelers",
"walt disney",
"southwest airlines",
"toppan printing",
"trend micro",
"apartment investment & management",
"the bank of new york mellon",
"jpmorgan chase",
"freeport-mcmoran",
"constellation brands",
"citizen holdings",
"comerica",
"nippon yusen",
"northern trust",
"idexx laboratories",
"pioneer",
"otsuka holdings",
"mitsui",
"brighthouse financial",
"mcdonald's",
"nasdaq,",
"nisshin seifun",
"cincinnati financial",
"coca-cola",
"kuraray",
"sysco",
"intel",
"robert half international",
"softbank",
"brown-forman",
"fleetcor technologies",
"mitsui chemicals",
"mitsui fudosan",
"boeing",
"jfe holdings",
"bitly",
"pvh",
"konami",
"toyobo",
"duke realty",
"mckesson",
"exelon",
"dentsu",
"alaska air",
"torchmark",
"allegion",
"centene",
"nisshin steel",
"the clorox",
"interpublic",
"broadridge financial solutions",
"american express",
"quanta services",
"comcast",
"exxonmobil",
"fujitsu",
"shizuoka bank",
"allstate",
"nomura holdings",
"apple",
"hewlett packard enterprise",
"alphabet class c",
"takara holdings",
"yandex",
"tencent qq",
"bridgestone",
"ecolab",
"boston properties",
"electronic arts",
"aozora bank",
"east japan railway",
"udr",
"invesco .",
"osaka gas",
"total system services",
"illumina",
"dai-ichi life",
"tiffany &",
"national oilwell varco",
"regions financial",
"incyte",
"ihi",
"alipay",
"fiserv",
"ingersoll-rand plc",
"tokuyama",
"marathon petroleum",
"ball",
"boston scientific",
"roper technologies",
"progressive",
"cbs",
"pinterest",
"loews",
"state street",
"iron mountain incorporated",
"showa shell sekiyu",
"twitter,",
"mitsubishi heavy industries",
"west japan railway",
"taobao",
"reddit",
"bing",
"texas instruments",
"amazon japan",
"hanesbrands",
"under armour class a",
"yum! brands",
"amerisourcebergen",
"at&t",
"teijin",
"asahi kasei",
"daiwa house industry",
"chevron",
"eaton",
"cummins",
"the mosaic",
"tmall",
"olympus",
"takashimaya",
"whatsapp",
"moody's",
"rakuten",
"news class a",
"dentsply sirona",
"google japan",
"newmont mining",
"american water works",
"asos.com",
"sompo holdings",
"kansai electric power",
"dena",
"celgene",
"broadcom",
"harley-davidson",
"zimmer biomet holdings",
"people's united financial",
"anadarko petroleum",
"twitch",
"extra space storage",
"tapestry,",
"baker hughes, a ge",
"apple",
"archer-daniels-midland",
"alexion pharmaceuticals",
"m&t bank",
"sohu",
"abbvie",
"raymond james financial",
"cigna",
"darden restaurants",
"western digital",
"kawasaki kisen kaisha",
"hartford financial svc.gp.",
"vornado realty trust",
"equinix",
"yokogawa electric",
"fast retailing",
"align technology",
"dominion energy",
"tdk",
"mail.ru",
"mid-america apartments",
"macerich",
"shiseido",
"kimco realty",
"chubb limited",
"daiichi sankyo",
"tokyo tatemono",
"keio",
"japan post holdings",
"sba communications",
"norfolk southern",
"nucor",
"mitsubishi logistics",
"ross stores",
"ube industries",
"coca-cola",
"international paper",
"ntt data",
"mitsubishi chemical holdings",
"yokohama rubber",
"universal health services,",
"colgate-palmolive",
"quora",
"fujikura",
"abiomed",
"prologis",
"ricoh",
"autozone",
"rockwell automation",
"msn",
"celanese",
"qualcomm",
"verisign",
"blogspot",
"prudential financial",
"fmc",
"eversource energy",
"xvideos",
"capital one financial",
"yaskawa electric",
"google turkey",
"general dynamics",
"subaru",
"bb&t",
"synopsys",
"twitter",
"kao",
"google uk",
"japan steel works",
"chiba bank",
"recruit holdings",
"oracle",
"the walt disney",
"packaging of america",
"cimarex energy",
"merck &",
"lincoln national",
"hologic",
"akamai technologies",
"netease",
"google russia",
"daiwa securities",
"federal realty investment trust",
"jd.com",
"dollar general",
"allergan, plc",
"hormel foods",
"tjx companies",
"comsys holdings",
"mitsubishi electric",
"foot locker",
"sony",
"church & dwight",
"crown castle international",
"conagra brands",
"tobu railway",
"devon energy",
"the hershey",
"mail.ru",
"accenture plc",
"masco",
"teleflex",
"u.s. bancorp",
"taisei",
"marsh & mclennan",
"aflac",
"alliance data systems",
"firstenergy",
"wec energy",
"sumitomo realty & development",
"shimizu",
"johnson & johnson",
"motorola solutions",
"vulcan materials",
"ppl",
"alibaba",
"philip morris international",
"nisource",
"keycorp",
"expedia",
"kla-tencor",
"c. h. robinson worldwide",
"macy's",
"best buy",
"toyota motor",
"zalando",
"seagate technology",
"nippon light metal",
"cerner",
"occidental petroleum",
"tokyu land",
"altria",
"csdn",
"amphenol",
"alexandria real estate equities",
"huntington bancshares",
"pacific metals",
"under armour class c",
"nippon telegraph and telephone",
"ventas",
"kinder morgan",
"chipotle mexican grill",
"omnicom",
"central japan railway",
"marriott int'l.",
"centurylink"
]