companies = [
"3m company",
"abbott laboratories",
"abbvie inc.",
"abiomed inc",
"accenture plc",
"activision blizzard",
"adobe systems inc",
"advanced micro devices inc",
"advance auto parts",
"aes corp",
"affiliated managers group inc",
"aflac inc",
"agilent technologies inc",
"air products & chemicals inc",
"akamai technologies inc",
"alaska air group inc",
"albemarle corp",
"alexandria real estate equities",
"alexion pharmaceuticals",
"align technology",
"allegion",
"allergan, plc",
"alliance data systems",
"alliant energy corp",
"allstate corp",
"alphabet inc class a",
"alphabet inc class c",
"altria group inc",
"amazon.com inc.",
"ameren corp",
"american airlines group",
"american electric power",
"american express co",
"american international group",
"american tower corp.",
"american water works company inc",
"ameriprise financial",
"amerisourcebergen corp",
"ametek inc.",
"amgen inc.",
"amphenol corp",
"anadarko petroleum corp",
"analog devices, inc.",
"ansys",
"anthem inc.",
"aon plc",
"a.o. smith corp",
"apache corporation",
"apartment investment & management ",
"apple inc.",
"applied materials inc.",
"aptiv plc",
"archer-daniels-midland co",
"arconic inc.",
"arista networks",
"arthur j. gallagher & co.",
"assurant",
"atmos energy corp",
"at&t inc.",
"autodesk inc.",
"automatic data processing",
"autozone inc",
"avalonbay communities, inc.",
"avery dennison corp",
"baker hughes, a ge company",
"ball corp",
"bank of america corp",
"the bank of new york mellon corp.",
"baxter international inc.",
"bb&t corporation",
"becton dickinson",
"berkshire hathaway",
"best buy co. inc.",
"biogen inc.",
"blackrock",
"block h&r",
"boeing company",
"booking holdings inc",
"borgwarner",
"boston properties",
"boston scientific",
"brighthouse financial inc",
"bristol-myers squibb",
"broadcom",
"broadridge financial solutions",
"brown-forman corp.",
"c. h. robinson worldwide",
"cabot oil & gas",
"cadence design systems",
"campbell soup",
"capital one financial",
"capri holdings",
"cardinal health inc.",
"carmax inc",
"carnival corp.",
"caterpillar inc.",
"cboe global markets",
"cbre group",
"cbs corp.",
"celanese corp.",
"celgene corp.",
"centene corporation",
"centerpoint energy",
"centurylink inc",
"cerner",
"cf industries holdings inc",
"charles schwab corporation",
"charter communications",
"chevron corp.",
"chipotle mexican grill",
"chubb limited",
"church & dwight",
"cigna corp.",
"cimarex energy",
"cincinnati financial",
"cintas corporation",
"cisco systems",
"citigroup inc.",
"citizens financial group",
"citrix systems",
"the clorox company",
"cme group inc.",
"cms energy",
"coca-cola company",
"cognizant technology solutions",
"colgate-palmolive",
"comcast corp.",
"comerica inc.",
"conagra brands",
"concho resources",
"conocophillips",
"consolidated edison",
"constellation brands",
"the cooper companies",
"copart inc",
"corning inc.",
"costco wholesale corp.",
"coty, inc",
"crown castle international corp.",
"csx corp.",
"cummins inc.",
"cvs health",
"d. r. horton",
"danaher corp.",
"darden restaurants",
"davita inc.",
"deere & co.",
"delta air lines inc.",
"dentsply sirona",
"devon energy",
"diamondback energy",
"digital realty trust inc",
"discover financial services",
"discovery inc. class a",
"discovery inc. class c",
"dish network",
"dollar general",
"dollar tree",
"dominion energy",
"dover corp.",
"dowdupont",
"dte energy co.",
"duke realty corp",
"duke energy",
"dxc technology",
"e*trade",
"eastman chemical",
"eaton corporation",
"ebay inc.",
"ecolab inc.",
"edison int'l",
"edwards lifesciences",
"electronic arts",
"emerson electric company",
"entergy corp.",
"eog resources",
"equifax inc.",
"equinix",
"equity residential",
"essex property trust, inc.",
"estee lauder cos.",
"evergy",
"eversource energy",
"everest re group ltd.",
"exelon corp.",
"expedia group",
"expeditors",
"extra space storage",
"exxon mobil corp.",
"f5 networks",
"facebook, inc.",
"fastenal co",
"federal realty investment trust",
"fedex corporation",
"fidelity national information services",
"fifth third bancorp",
"firstenergy corp",
"first republic bank",
"fiserv inc",
"fleetcor technologies inc",
"flir systems",
"flowserve corporation",
"fluor corp.",
"fmc corporation",
"foot locker inc",
"ford motor",
"fortinet",
"fortive corp",
"fortune brands home & security",
"franklin resources",
"freeport-mcmoran inc.",
"gap inc.",
"garmin ltd.",
"gartner inc",
"general dynamics",
"general electric",
"general mills",
"general motors",
"genuine parts",
"gilead sciences",
"global payments inc.",
"goldman sachs group",
"grainger (w.w.) inc.",
"halliburton co.",
"hanesbrands inc",
"harley-davidson",
"harris corporation",
"hartford financial svc.gp.",
"hasbro inc.",
"hca holdings",
"hcp inc.",
"helmerich & payne",
"henry schein",
"the hershey company",
"hess corporation",
"hewlett packard enterprise",
"hilton worldwide holdings inc",
"hollyfrontier corp",
"hologic",
"home depot",
"honeywell int'l inc.",
"hormel foods corp.",
"host hotels & resorts",
"hp inc.",
"humana inc.",
"huntington bancshares",
"huntington ingalls industries",
"idexx laboratories",
"ihs markit ltd.",
"illinois tool works",
"illumina inc",
"ingersoll-rand plc",
"intel corp.",
"intercontinental exchange",
"international business machines",
"incyte",
"international paper",
"interpublic group",
"intl flavors & fragrances",
"intuit inc. ",
"intuitive surgical inc.",
"invesco ltd.",
"ipg photonics corp.",
"iqvia holdings inc.",
"iron mountain incorporated",
"jack henry & associates inc",
"jacobs engineering group",
"j. b. hunt transport services",
"jefferies financial group",
"jm smucker",
"johnson & johnson",
"johnson controls international",
"jpmorgan chase & co.",
"juniper networks",
"kansas city southern",
"kellogg co.",
"keycorp",
"keysight technologies",
"kimberly-clark",
"kimco realty",
"kinder morgan",
"kla-tencor corp.",
"kohl's corp.",
"kraft heinz co",
"kroger co.",
"l brands inc.",
"l-3 communications holdings",
"laboratory corp. of america holding",
"lam research",
"lamb weston holdings inc",
"leggett & platt",
"lennar corp.",
"lilly (eli) & co.",
"lincoln national",
"linde plc",
"lkq corporation",
"lockheed martin corp.",
"loews corp.",
"lowe's cos.",
"lyondellbasell",
"m&t bank corp.",
"macerich",
"macy's inc.",
"marathon oil corp.",
"marathon petroleum",
"marriott int'l.",
"marsh & mclennan",
"martin marietta materials",
"masco corp.",
"mastercard inc.",
"mattel inc.",
"mccormick & co.",
"maxim integrated products inc",
"mcdonald's corp.",
"mckesson corp.",
"medtronic plc",
"merck & co.",
"metlife inc.",
"mettler toledo",
"mgm resorts international",
"microchip technology",
"micron technology",
"microsoft corp.",
"mid-america apartments",
"mohawk industries",
"molson coors brewing company",
"mondelez international",
"monster beverage",
"moody's corp",
"morgan stanley",
"the mosaic company",
"motorola solutions inc.",
"msci inc",
"mylan n.v.",
"nasdaq, inc.",
"national oilwell varco inc.",
"nektar therapeutics",
"netapp",
"netflix inc.",
"newell brands",
"newmont mining corporation",
"news corp. class a",
"news corp. class b",
"nextera energy",
"nielsen holdings",
"nike",
"nisource inc.",
"noble energy inc",
"nordstrom",
"norfolk southern corp.",
"northern trust corp.",
"northrop grumman corp.",
"norwegian cruise line",
"nrg energy",
"nucor corp.",
"nvidia corporation",
"o'reilly automotive",
"occidental petroleum",
"omnicom group",
"oneok",
"oracle corp.",
"paccar inc.",
"packaging corporation of america",
"parker-hannifin",
"paychex inc.",
"paypal",
"pentair plc",
"people's united financial",
"pepsico inc.",
"perkinelmer",
"perrigo",
"pfizer inc.",
"philip morris international",
"phillips 66",
"pinnacle west capital",
"pioneer natural resources",
"pnc financial services",
"polo ralph lauren corp.",
"ppg industries",
"ppl corp.",
"principal financial group",
"procter & gamble",
"progressive corp.",
"prologis",
"prudential financial",
"public serv. enterprise inc.",
"public storage",
"pulte homes inc.",
"pvh corp.",
"qorvo",
"quanta services inc.",
"qualcomm inc.",
"quest diagnostics",
"raymond james financial inc.",
"raytheon co.",
"realty income corporation",
"red hat inc.",
"regency centers corporation",
"regeneron",
"regions financial corp.",
"republic services inc",
"resmed",
"robert half international",
"rockwell automation inc.",
"rollins inc.",
"roper technologies",
"ross stores",
"royal caribbean cruises ltd",
"salesforce.com",
"sba communications",
"schlumberger ltd.",
"seagate technology",
"sealed air",
"sempra energy",
"sherwin-williams",
"simon property group inc",
"skyworks solutions",
"sl green realty",
"snap-on",
"southern co.",
"southwest airlines",
"s&p global, inc.",
"stanley black & decker",
"starbucks corp.",
"state street corp.",
"stryker corp.",
"suntrust banks",
"svb financial",
"symantec corp.",
"synchrony financial",
"synopsys inc.",
"sysco corp.",
"t. rowe price group",
"take-two interactive",
"tapestry, inc.",
"target corp.",
"te connectivity ltd.",
"technipfmc",
"teleflex inc",
"texas instruments",
"textron inc.",
"thermo fisher scientific",
"tiffany & co.",
"twitter, inc.",
"tjx companies inc.",
"torchmark corp.",
"total system services",
"tractor supply company",
"transdigm group",
"the travelers companies inc.",
"tripadvisor",
"twenty-first century fox class a",
"twenty-first century fox class b",
"tyson foods",
"udr inc",
"ulta beauty",
"u.s. bancorp",
"under armour class a",
"under armour class c",
"union pacific",
"united continental holdings",
"united health group inc.",
"united parcel service",
"united rentals, inc.",
"united technologies",
"universal health services, inc.",
"unum group",
"v.f. corp.",
"valero energy",
"varian medical systems",
"ventas inc",
"verisign inc.",
"verisk analytics",
"verizon communications",
"vertex pharmaceuticals inc",
"viacom inc.",
"visa inc.",
"vornado realty trust",
"vulcan materials",
"wabtec corporation",
"walmart",
"walgreens boots alliance",
"the walt disney company",
"waste management inc.",
"waters corporation",
"wec energy group inc",
"wellcare",
"wells fargo",
"welltower inc.",
"western digital",
"western union co",
"westrock",
"weyerhaeuser",
"whirlpool corp.",
"williams cos.",
"willis towers watson",
"wynn resorts ltd",
"xcel energy inc",
"xerox",
"xilinx",
"xylem inc.",
"yum! brands inc",
"zimmer biomet holdings",
"zions bancorp",
"zoetis"
]