companies = [
"aptiv plc",
"intl flavors & fragrances",
"intuitive surgical",
"maxim integrated products",
"deere &",
"fortive",
"cisco systems",
"tokuyama",
"pacific metals",
"alliant energy",
"yamaha",
"franklin resources",
"whirlpool",
"albemarle",
"westrock",
"jpmorgan chase",
"walgreens boots alliance",
"verisk analytics",
"union pacific",
"nippon paper ,",
"haseko",
"kawasaki heavy industries",
"the bank of new york mellon",
"m&t bank",
"microsoft",
"mitsubishi ufj financial",
"chevron",
"halliburton",
"credit saison",
"intercontinental exchange",
"jd.com",
"fanuc",
"eog resources",
"mattel",
"oneok",
"ppl",
"campbell soup",
"svb financial",
"fortune brands home & security",
"hitachi zōsen",
"devon energy",
"tosoh",
"willis towers watson",
"daikin industries",
"goldman sachs",
"sumitomo mitsui trust holdings",
"nippon light metal",
"international paper",
"gilead sciences",
"becton dickinson",
"american tower",
"huntington bancshares",
"general electric",
"avery dennison",
"iron mountain incorporated",
"sky perfect jsat holdings",
"tractor supply",
"udr",
"crown castle international",
"aflac",
"mitsubishi electric",
"mckesson",
"ball",
"chipotle mexican grill",
"cboe global markets",
"broadridge financial solutions",
"suntrust banks",
"ulta beauty",
"bb&t",
"amazon.com",
"copart",
"ventas",
"sumitomo dainippon pharma",
"exelon",
"gartner",
"arconic",
"mitsubishi chemical holdings",
"3m",
"martin marietta materials",
"fluor",
"nielsen holdings",
"unum",
"automatic data processing",
"a.o. smith",
"flowserve",
"central japan railway",
"grainger (w.w.)",
"alexandria real estate equities",
"principal financial",
"sherwin-williams",
"mitsubishi estate",
"affiliated managers",
"groupon",
"canon",
"synchrony financial",
"diamondback energy",
"pfizer",
"mitsui mining & smelting",
"b2w",
"harley-davidson",
"mitsui o.s.k. lines",
"gap",
"boston properties",
"isetan mitsukoshi holdings",
"obayashi",
"secom",
"torchmark",
"inpex",
"mitsui fudosan",
"coty,",
"texas instruments",
"familymart uny holdings",
"ntt data",
"mail.ru",
"merck &",
"applied materials",
"qorvo",
"american airlines",
"corning",
"alaska air",
"centene",
"nextera energy",
"qualcomm",
"resmed",
"odakyu electric railway",
"casio computer",
"nisshin steel",
"mastercard",
"vornado realty trust",
"skyworks solutions",
"nasdaq,",
"noble energy",
"eaton",
"cbre",
"bristol-myers squibb",
"seven & i holdings",
"tokyu land",
"zoetis",
"flipkart",
"nvidia",
"ameren",
"cabot oil & gas",
"capri holdings",
"nippon express",
"host hotels & resorts",
"masco",
"tokyo tatemono",
"tobu railway",
"fiserv",
"eastman chemical",
"dai-ichi life",
"mizuho financial",
"kroger",
"ebara",
"mgm resorts international",
"intel",
"furukawa electric",
"mitsubishi materials",
"nissan motor",
"dowa holdings",
"abiomed",
"verizon communications",
"sompo holdings",
"ebay",
"jacobs engineering",
"tjx companies",
"discovery class a",
"rakuten",
"brighthouse financial",
"autozone",
"subaru",
"o'reilly automotive",
"brown-forman",
"l-3 communications holdings",
"d. r. horton",
"itochu",
"northern trust",
"centerpoint energy",
"vulcan materials",
"lkq",
"snap-on",
"abbott laboratories",
"united rentals,",
"yokogawa electric",
"waters",
"alibaba",
"panasonic",
"pinnacle west capital",
"dai nippon printing",
"nippon electric glass",
"delta air lines",
"kirin brewery",
"public serv. enterprise",
"hewlett packard enterprise",
"people's united financial",
"resona holdings",
"perkinelmer",
"concordia financial",
"henry schein",
"visa",
"osaka gas",
"sempra energy",
"humana",
"cadence design systems",
"chubb limited",
"unitika",
"seiko epson",
"tokio marine holdings",
"ube industries",
"ipg photonics",
"freeport-mcmoran",
"prologis",
"packaging of america",
"the travelers companies",
"amerisourcebergen",
"dainippon screen",
"danaher",
"hologic",
"quest diagnostics",
"u.s. bancorp",
"best buy",
"realty income",
"emerson electric",
"visa",
"jgc",
"sl green realty",
"nippon steel",
"consolidated edison",
"paccar",
"kikkoman",
"bloomberg l.p.",
"sumitomo osaka cement",
"monster beverage",
"celanese",
"abbvie",
"nomura holdings",
"conagra brands",
"pulte homes",
"nikon",
"boston scientific",
"national oilwell varco",
"hilton worldwide holdings",
"regency centers",
"aon plc",
"toyobo",
"dentsu",
"nichirei",
"celgene",
"aes",
"micron technology",
"hino motors",
"broadcom",
"royal caribbean cruises",
"t&d holdings",
"flir systems",
"jpmorgan chase &",
"anthem",
"garmin .",
"j. front retailing",
"ms&ad insurance",
"nsk",
"idexx laboratories",
"s&p global,",
"seagate technology",
"southwest airlines",
"comerica",
"valero energy",
"kubota",
"american express",
"activision blizzard",
"chugai pharmaceutical",
"kraft heinz",
"hitachi",
"mitsubishi motors",
"dish network",
"alphabet class c",
"carmax",
"expedia",
"konica minolta holdings",
"wellcare",
"toyota tsusho",
"baidu",
"jack henry & associates",
"kyocera",
"keycorp",
"west japan railway",
"jfe holdings",
"analog devices,",
"align technology",
"konami",
"apache",
"the cooper companies",
"metlife",
"shizuoka bank",
"alps electric",
"hca holdings",
"borgwarner",
"walt disney",
"marathon oil",
"ntt docomo",
"simon property",
"goldman sachs",
"astellas pharma",
"accenture plc",
"williams cos.",
"the home depot",
"microsoft",
"xilinx",
"ebay",
"taiyo yuden",
"mitsui chemicals",
"ecolab",
"roper technologies",
"nike",
"sysco",
"cardinal health",
"ford motor",
"tyson foods",
"the walt disney",
"jm smucker",
"zimmer biomet holdings",
"norfolk southern",
"amphenol",
"ansys",
"toppan printing",
"mitsui engineering & shipbuilding",
"aeon",
"ibm",
"interpublic",
"kddi",
"estee lauder cos.",
"cimarex energy",
"anadarko petroleum",
"alphabet class a",
"first republic bank",
"medtronic plc",
"invesco .",
"federal realty investment trust",
"cincinnati financial",
"occidental petroleum",
"japan tobacco",
"keio",
"transdigm",
"chubu electric power",
"t. rowe price",
"ihi",
"dentsply sirona",
"wabtec",
"fidelity national information services",
"essex property trust,",
"lilly (eli) &",
"sony",
"hp",
"showa denko",
"sumco",
"sumitomo",
"technipfmc",
"f5 networks",
"cf industries holdings",
"motorola solutions",
"nordstrom",
"welltower",
"meituan-dianping",
"macerich",
"cvs health",
"showa shell sekiyu",
"cme",
"dollar tree",
"extra space storage",
"nitto denko",
"mitsui",
"capital one financial",
"mccormick &",
"robert half international",
"expedia",
"keisei electric railway",
"thermo fisher scientific",
"shimizu",
"honeywell int'l",
"advance auto parts",
"all nippon airways",
"takara holdings",
"furukawa",
"tiffany &",
"berkshire hathaway",
"schlumberger .",
"tencent",
"twenty-first century fox class a",
"lincoln national",
"autodesk",
"discovery class c",
"workday",
"intel",
"coca-cola",
"taiheiyo cement",
"fukuoka financial",
"dena",
"otsuka holdings",
"altria",
"wells fargo",
"lockheed martin",
"illinois tool works",
"chiyoda",
"nippon sheet glass",
"nippon kayaku",
"suzuki motor",
"harris",
"boeing",
"expeditors",
"xylem",
"loews",
"conocophillips",
"united technologies",
"toyo seikan kaisha",
"tokyo electron",
"fuji electric holdings",
"trend micro",
"equifax",
"facebook,",
"lowe's cos.",
"constellation brands",
"unitedhealth",
"global payments",
"asahi breweries",
"mitsubishi",
"wynn resorts",
"viacom",
"eisai",
"xcel energy",
"mcdonald's",
"iqvia holdings",
"ricoh",
"concho resources",
"equity residential",
"eversource energy",
"lamb weston holdings",
"toto .",
"marathon petroleum",
"phillips 66",
"booking",
"nissan chemical industries",
"tokyo gas",
"western union",
"biogen",
"hollyfrontier",
"kohl's",
"nucor",
"comcast",
"netease",
"newmont mining",
"oki electric industry",
"yamato holdings",
"pepsico",
"apple",
"fmc",
"netflix",
"omnicom",
"laboratory of america holding",
"exxon mobil",
"sba communications",
"regeneron",
"hcp",
"mcdonald's",
"okuma holdings",
"jtekt",
"akamai technologies",
"dxc technology",
"sapporo holdings",
"perrigo",
"e*trade",
"starbucks",
"amazon",
"centurylink",
"ihs markit .",
"republic services",
"asahi kasei",
"target",
"zions bancorp",
"wec energy",
"daiwa securities",
"recruit holdings",
"naver",
"nrg energy",
"lennar",
"charter communications",
"bank of america",
"twitter,",
"fujitsu",
"davita",
"tokyo dome",
"archer-daniels-midland",
"norwegian cruise line",
"citigroup",
"molson coors brewing",
"sumitomo realty & development",
"agilent technologies",
"boeing",
"incyte",
"3m",
"quanta services",
"alexion pharmaceuticals",
"colgate-palmolive",
"sony financial",
"block h&r",
"tokyo electric power",
"daiichi sankyo",
"american water works",
"toyota motor",
"keysight technologies",
"symantec",
"dowdupont",
"atmos energy",
"takeda pharmaceutical",
"softbank",
"amgen",
"arista networks",
"kuraray",
"discover financial services",
"daiwa house industry",
"walmart",
"church & dwight",
"comsys holdings",
"southern",
"teleflex",
"mitsubishi logistics",
"american electric power",
"genuine parts",
"nisshin seifun",
"state street",
"costco wholesale",
"duke realty",
"fastenal",
"general motors",
"paypal",
"ajinomoto",
"american international",
"northrop grumman",
"the hershey",
"dollar general",
"stryker",
"international business machines",
"mettler toledo",
"pentair plc",
"komatsu",
"mid-america apartments",
"ameriprise financial",
"citrix systems",
"johnson & johnson",
"marsh & mclennan",
"procter & gamble",
"teijin",
"illumina",
"nec",
"kawasaki kisen kaisha",
"nisshinbo holdings",
"kansai electric power",
"assurant",
"firstenergy",
"polo ralph lauren",
"advanced micro devices",
"juniper networks",
"csx",
"sealed air",
"the mosaic",
"kyowa hakko kirin",
"cigna",
"fortinet",
"synopsys",
"tapestry,",
"blackrock",
"apple",
"philip morris international",
"parker-hannifin",
"hanesbrands",
"carnival",
"dominion energy",
"marui",
"mylan n.v.",
"cintas",
"general dynamics",
"rockwell automation",
"kimberly-clark",
"under armour class c",
"uber",
"netflix",
"pvh",
"marubeni",
"newell brands",
"yamaha motor",
"united parcel service",
"lyondellbasell",
"ingersoll-rand plc",
"edwards lifesciences",
"facebook",
"johnson controls international",
"ngk insulators",
"taisei",
"charles schwab",
"mohawk industries",
"sumitomo mitsui financial",
"kinder morgan",
"te connectivity .",
"jefferies financial",
"j. b. hunt transport services",
"morgan stanley",
"olympus",
"v.f.",
"honda motor",
"twenty-first century fox class b",
"gs yuasa",
"helmerich & payne",
"varian medical systems",
"tokyu",
"fedex",
"raymond james financial",
"avalonbay communities,",
"moody's",
"kimco realty",
"caterpillar",
"oracle",
"stanley black & decker",
"american express",
"east japan railway",
"toho",
"adobe systems",
"arthur j. gallagher &",
"citizens financial",
"mondelez international",
"nippon telegraph and telephone",
"kellogg",
"news class b",
"cbs",
"sojitz",
"nippon yusen",
"l brands",
"verizon",
"minebea",
"shinsei bank",
"sekisui house",
"huntington ingalls industries",
"terumo",
"fifth third bancorp",
"chiba bank",
"maruha nichiro holdings",
"xerox",
"public storage",
"progressive",
"the clorox",
"mitsubishi heavy industries",
"alphabet",
"japan steel works",
"alliance data systems",
"isuzu motors",
"nisource",
"hormel foods",
"cummins",
"twitter",
"intuit",
"msci",
"sumitomo chemical",
"red hat",
"hasbro",
"tripadvisor",
"advantest",
"textron",
"pioneer natural resources",
"kla-tencor",
"weyerhaeuser",
"takashimaya",
"baker hughes, a ge",
"allergan, plc",
"lam research",
"pfizer",
"foot locker",
"zalando",
"kajima",
"united health",
"fujifilm holdings",
"regions financial",
"ross stores",
"shiseido",
"fleetcor technologies",
"electronic arts",
"raytheon",
"matsui securities",
"exxonmobil",
"shionogi",
"united continental holdings",
"evergy",
"airbnb",
"caterpillar",
"edison int'l",
"travelers",
"universal health services,",
"aozora bank",
"tokai carbon",
"under armour class a",
"prudential financial",
"duke energy",
"cerner",
"darden restaurants",
"general mills",
"kobe steel",
"nektar therapeutics",
"meiji holdings",
"at&t",
"yahoo japan",
"edreams odigeo",
"toho zinc",
"news class a",
"yokohama rubber",
"japan post holdings",
"entergy",
"digital realty trust",
"bridgestone",
"yum! brands",
"verisign",
"denso",
"air products & chemicals",
"salesforce.com",
"asahi glass",
"asos.com",
"dover",
"allegion",
"chevron",
"rollins",
"kansas city southern",
"hartford financial svc.gp.",
"western digital",
"allstate",
"pioneer",
"oji paper",
"amada .",
"nippon suisan kaisha",
"ametek",
"nippon meat packers",
"toray industries",
"hess",
"citizen holdings",
"pnc financial services",
"dte energy",
"total system services",
"merck &",
"ntn",
"waste management",
"sumitomo electric industries",
"mazda motor",
"kao",
"sumitomo heavy industries",
"marriott int'l.",
"cognizant technology solutions",
"tdk",
"ppg industries",
"cms energy",
"netapp",
"spotify",
"apartment investment & management",
"booking holdings",
"fujikura",
"equinix",
"vertex pharmaceuticals",
"sumitomo metal mining",
"c. h. robinson worldwide",
"yandex",
"everest re .",
"jxtg holdings",
"coca-cola",
"linde plc",
"home depot",
"macy's",
"paychex",
"shin-etsu chemical",
"fast retailing",
"microchip technology",
"hitachi construction machinery",
"baxter international",
"leggett & platt",
"yaskawa electric",
"take-two interactive",
"denki kagaku kogyo"
]