companies = [
"aptiv plc",
"intl flavors & fragrances",
"intuitive surgical inc.",
"maxim integrated products inc",
"deere & co.",
"fortive corp",
"cisco systems",
"tokuyama corporation",
"pacific metals",
"alliant energy corp",
"yamaha",
"franklin resources",
"whirlpool corp.",
"albemarle corp",
"westrock",
"jpmorgan chase",
"walgreens boots alliance",
"verisk analytics",
"union pacific",
"nippon paper group, inc.",
"haseko corp.",
"kawasaki heavy industries",
"the bank of new york mellon corp.",
"m&t bank corp.",
"microsoft",
"mitsubishi ufj financial group",
"chevron",
"halliburton co.",
"credit saison",
"intercontinental exchange",
"jd.com",
"fanuc",
"eog resources",
"mattel inc.",
"oneok",
"ppl corp.",
"campbell soup",
"svb financial",
"fortune brands home & security",
"hitachi zōsen",
"devon energy",
"tosoh",
"willis towers watson",
"daikin industries",
"goldman sachs group",
"sumitomo mitsui trust holdings",
"nippon light metal",
"international paper",
"gilead sciences",
"becton dickinson",
"american tower corp.",
"huntington bancshares",
"general electric",
"avery dennison corp",
"iron mountain incorporated",
"sky perfect jsat holdings inc.",
"tractor supply company",
"udr inc",
"crown castle international corp.",
"aflac inc",
"mitsubishi electric",
"mckesson corp.",
"ball corp",
"chipotle mexican grill",
"cboe global markets",
"broadridge financial solutions",
"suntrust banks",
"ulta beauty",
"bb&t corporation",
"amazon.com inc.",
"copart inc",
"ventas inc",
"sumitomo dainippon pharma",
"exelon corp.",
"gartner inc",
"arconic inc.",
"mitsubishi chemical holdings",
"3m",
"martin marietta materials",
"fluor corp.",
"nielsen holdings",
"unum group",
"automatic data processing",
"a.o. smith corp",
"flowserve corporation",
"central japan railway company",
"grainger (w.w.) inc.",
"alexandria real estate equities",
"principal financial group",
"sherwin-williams",
"mitsubishi estate",
"affiliated managers group inc",
"groupon",
"canon",
"synchrony financial",
"diamondback energy",
"pfizer",
"mitsui mining & smelting",
"b2w",
"harley-davidson",
"mitsui o.s.k. lines",
"gap inc.",
"boston properties",
"isetan mitsukoshi holdings",
"obayashi",
"secom",
"torchmark corp.",
"inpex",
"mitsui fudosan",
"coty, inc",
"texas instruments",
"familymart uny holdings",
"ntt data",
"mail.ru",
"merck & company",
"applied materials inc.",
"qorvo",
"american airlines group",
"corning inc.",
"alaska air group inc",
"centene corporation",
"nextera energy",
"qualcomm inc.",
"resmed",
"odakyu electric railway",
"casio computer",
"nisshin steel",
"mastercard inc.",
"vornado realty trust",
"skyworks solutions",
"nasdaq, inc.",
"noble energy inc",
"eaton corporation",
"cbre group",
"bristol-myers squibb",
"seven & i holdings",
"tokyu land",
"zoetis",
"flipkart",
"nvidia corporation",
"ameren corp",
"cabot oil & gas",
"capri holdings",
"nippon express",
"host hotels & resorts",
"masco corp.",
"tokyo tatemono",
"tobu railway",
"fiserv inc",
"eastman chemical",
"dai-ichi life",
"mizuho financial group",
"kroger co.",
"ebara",
"mgm resorts international",
"intel corp.",
"furukawa electric",
"mitsubishi materials",
"nissan motor",
"dowa holdings",
"abiomed inc",
"verizon communications",
"sompo holdings",
"ebay inc.",
"jacobs engineering group",
"tjx companies inc.",
"discovery inc. class a",
"rakuten",
"brighthouse financial inc",
"autozone inc",
"subaru",
"o'reilly automotive",
"brown-forman corp.",
"l-3 communications holdings",
"d. r. horton",
"itochu",
"northern trust corp.",
"centerpoint energy",
"vulcan materials",
"lkq corporation",
"snap-on",
"abbott laboratories",
"united rentals, inc.",
"yokogawa electric",
"waters corporation",
"alibaba",
"panasonic",
"pinnacle west capital",
"dai nippon printing",
"nippon electric glass",
"delta air lines inc.",
"kirin brewery",
"public serv. enterprise inc.",
"hewlett packard enterprise",
"people's united financial",
"resona holdings",
"perkinelmer",
"concordia financial group",
"henry schein",
"visa inc.",
"osaka gas",
"sempra energy",
"humana inc.",
"cadence design systems",
"chubb limited",
"unitika",
"seiko epson",
"tokio marine holdings",
"ube industries",
"ipg photonics corp.",
"freeport-mcmoran inc.",
"prologis",
"packaging corporation of america",
"the travelers companies inc.",
"amerisourcebergen corp",
"dainippon screen",
"danaher corp.",
"hologic",
"quest diagnostics",
"u.s. bancorp",
"best buy co. inc.",
"realty income corporation",
"emerson electric company",
"visa",
"jgc corporation",
"sl green realty",
"nippon steel",
"consolidated edison",
"paccar inc.",
"kikkoman",
"bloomberg l.p.",
"sumitomo osaka cement",
"monster beverage",
"celanese corp.",
"abbvie inc.",
"nomura holdings",
"conagra brands",
"pulte homes inc.",
"nikon",
"boston scientific",
"national oilwell varco inc.",
"hilton worldwide holdings inc",
"regency centers corporation",
"aon plc",
"toyobo",
"dentsu",
"nichirei",
"celgene corp.",
"aes corp",
"micron technology",
"hino motors",
"broadcom",
"royal caribbean cruises ltd",
"t&d holdings",
"flir systems",
"jpmorgan chase & co.",
"anthem inc.",
"garmin ltd.",
"j. front retailing",
"ms&ad insurance group",
"nsk",
"idexx laboratories",
"s&p global, inc.",
"seagate technology",
"southwest airlines",
"comerica inc.",
"valero energy",
"kubota",
"american express",
"activision blizzard",
"chugai pharmaceutical",
"kraft heinz co",
"hitachi",
"mitsubishi motors",
"dish network",
"alphabet inc class c",
"carmax inc",
"expedia group",
"konica minolta holdings",
"wellcare",
"toyota tsusho",
"baidu",
"jack henry & associates inc",
"kyocera",
"keycorp",
"west japan railway",
"jfe holdings",
"analog devices, inc.",
"align technology",
"konami",
"apache corporation",
"the cooper companies",
"metlife inc.",
"shizuoka bank",
"alps electric",
"hca holdings",
"borgwarner",
"walt disney",
"marathon oil corp.",
"ntt docomo",
"simon property group inc",
"goldman sachs",
"astellas pharma",
"accenture plc",
"williams cos.",
"the home depot",
"microsoft corp.",
"xilinx",
"ebay",
"taiyo yuden",
"mitsui chemicals",
"ecolab inc.",
"roper technologies",
"nike",
"sysco corp.",
"cardinal health inc.",
"ford motor",
"tyson foods",
"the walt disney company",
"jm smucker",
"zimmer biomet holdings",
"norfolk southern corp.",
"amphenol corp",
"ansys",
"toppan printing",
"mitsui engineering & shipbuilding",
"aeon",
"ibm",
"interpublic group",
"kddi",
"estee lauder cos.",
"cimarex energy",
"anadarko petroleum corp",
"alphabet inc class a",
"first republic bank",
"medtronic plc",
"invesco ltd.",
"federal realty investment trust",
"cincinnati financial",
"occidental petroleum",
"japan tobacco",
"keio",
"transdigm group",
"chubu electric power",
"t. rowe price group",
"ihi",
"dentsply sirona",
"wabtec corporation",
"fidelity national information services",
"essex property trust, inc.",
"lilly (eli) & co.",
"sony",
"hp inc.",
"showa denko",
"sumco",
"sumitomo",
"technipfmc",
"f5 networks",
"cf industries holdings inc",
"motorola solutions inc.",
"nordstrom",
"welltower inc.",
"meituan-dianping",
"macerich",
"cvs health",
"showa shell sekiyu",
"cme group inc.",
"dollar tree",
"extra space storage",
"nitto denko",
"mitsui",
"capital one financial",
"mccormick & co.",
"robert half international",
"expedia",
"keisei electric railway",
"thermo fisher scientific",
"shimizu",
"honeywell int'l inc.",
"advance auto parts",
"all nippon airways",
"takara holdings",
"furukawa",
"tiffany & co.",
"berkshire hathaway",
"schlumberger ltd.",
"tencent",
"twenty-first century fox class a",
"lincoln national",
"autodesk inc.",
"discovery inc. class c",
"workday",
"intel",
"coca-cola company",
"taiheiyo cement",
"fukuoka financial group",
"dena",
"otsuka holdings co.",
"altria group inc",
"wells fargo",
"lockheed martin corp.",
"illinois tool works",
"chiyoda",
"nippon sheet glass",
"nippon kayaku",
"suzuki motor",
"harris corporation",
"boeing",
"expeditors",
"xylem inc.",
"loews corp.",
"conocophillips",
"united technologies",
"toyo seikan kaisha",
"tokyo electron",
"fuji electric holdings",
"trend micro",
"equifax inc.",
"facebook, inc.",
"lowe's cos.",
"constellation brands",
"unitedhealth group",
"global payments inc.",
"asahi breweries",
"mitsubishi",
"wynn resorts ltd",
"viacom inc.",
"eisai",
"xcel energy inc",
"mcdonald's corp.",
"iqvia holdings inc.",
"ricoh",
"concho resources",
"equity residential",
"eversource energy",
"lamb weston holdings inc",
"toto ltd.",
"marathon petroleum",
"phillips 66",
"booking",
"nissan chemical industries",
"tokyo gas",
"western union co",
"biogen inc.",
"hollyfrontier corp",
"kohl's corp.",
"nucor corp.",
"comcast corp.",
"netease",
"newmont mining corporation",
"oki electric industry",
"yamato holdings",
"pepsico inc.",
"apple",
"fmc corporation",
"netflix",
"omnicom group",
"laboratory corp. of america holding",
"exxon mobil corp.",
"sba communications",
"regeneron",
"hcp inc.",
"mcdonald's",
"okuma holdings",
"jtekt",
"akamai technologies inc",
"dxc technology",
"sapporo holdings",
"perrigo",
"e*trade",
"starbucks corp.",
"amazon",
"centurylink inc",
"ihs markit ltd.",
"republic services inc",
"asahi kasei",
"target corp.",
"zions bancorp",
"wec energy group inc",
"daiwa securities group",
"recruit holdings",
"naver",
"nrg energy",
"lennar corp.",
"charter communications",
"bank of america corp",
"twitter, inc.",
"fujitsu",
"davita inc.",
"tokyo dome",
"archer-daniels-midland co",
"norwegian cruise line",
"citigroup inc.",
"molson coors brewing company",
"sumitomo realty & development",
"agilent technologies inc",
"boeing company",
"incyte",
"3m company",
"quanta services inc.",
"alexion pharmaceuticals",
"colgate-palmolive",
"sony financial",
"block h&r",
"tokyo electric power",
"daiichi sankyo",
"american water works company inc",
"toyota motor",
"keysight technologies",
"symantec corp.",
"dowdupont",
"atmos energy corp",
"takeda pharmaceutical company",
"softbank",
"amgen inc.",
"arista networks",
"kuraray",
"discover financial services",
"daiwa house industry",
"walmart",
"church & dwight",
"comsys holdings",
"southern co.",
"teleflex inc",
"mitsubishi logistics",
"american electric power",
"genuine parts",
"nisshin seifun group",
"state street corp.",
"costco wholesale corp.",
"duke realty corp",
"fastenal co",
"general motors",
"paypal",
"ajinomoto",
"american international group",
"northrop grumman corp.",
"the hershey company",
"dollar general",
"stryker corp.",
"international business machines",
"mettler toledo",
"pentair plc",
"komatsu",
"mid-america apartments",
"ameriprise financial",
"citrix systems",
"johnson & johnson",
"marsh & mclennan",
"procter & gamble",
"teijin",
"illumina inc",
"nec",
"kawasaki kisen kaisha",
"nisshinbo holdings",
"kansai electric power",
"assurant",
"firstenergy corp",
"polo ralph lauren corp.",
"advanced micro devices inc",
"juniper networks",
"csx corp.",
"sealed air",
"the mosaic company",
"kyowa hakko kirin",
"cigna corp.",
"fortinet",
"synopsys inc.",
"tapestry, inc.",
"blackrock",
"apple inc.",
"philip morris international",
"parker-hannifin",
"hanesbrands inc",
"carnival corp.",
"dominion energy",
"marui group",
"mylan n.v.",
"cintas corporation",
"general dynamics",
"rockwell automation inc.",
"kimberly-clark",
"under armour class c",
"uber",
"netflix inc.",
"pvh corp.",
"marubeni",
"newell brands",
"yamaha motor",
"united parcel service",
"lyondellbasell",
"ingersoll-rand plc",
"edwards lifesciences",
"facebook",
"johnson controls international",
"ngk insulators",
"taisei",
"charles schwab corporation",
"mohawk industries",
"sumitomo mitsui financial group",
"kinder morgan",
"te connectivity ltd.",
"jefferies financial group",
"j. b. hunt transport services",
"morgan stanley",
"olympus",
"v.f. corp.",
"honda motor",
"twenty-first century fox class b",
"gs yuasa",
"helmerich & payne",
"varian medical systems",
"tokyu",
"fedex corporation",
"raymond james financial inc.",
"avalonbay communities, inc.",
"moody's corp",
"kimco realty",
"caterpillar",
"oracle corp.",
"stanley black & decker",
"american express co",
"east japan railway company",
"toho",
"adobe systems inc",
"arthur j. gallagher & co.",
"citizens financial group",
"mondelez international",
"nippon telegraph and telephone",
"kellogg co.",
"news corp. class b",
"cbs corp.",
"sojitz",
"nippon yusen",
"l brands inc.",
"verizon",
"minebea",
"shinsei bank",
"sekisui house",
"huntington ingalls industries",
"terumo",
"fifth third bancorp",
"chiba bank",
"maruha nichiro holdings",
"xerox",
"public storage",
"progressive corp.",
"the clorox company",
"mitsubishi heavy industries",
"alphabet inc.",
"japan steel works",
"alliance data systems",
"isuzu motors",
"nisource inc.",
"hormel foods corp.",
"cummins inc.",
"twitter",
"intuit inc. ",
"msci inc",
"sumitomo chemical",
"red hat inc.",
"hasbro inc.",
"tripadvisor",
"advantest",
"textron inc.",
"pioneer natural resources",
"kla-tencor corp.",
"weyerhaeuser",
"takashimaya",
"baker hughes, a ge company",
"allergan, plc",
"lam research",
"pfizer inc.",
"foot locker inc",
"zalando",
"kajima",
"united health group inc.",
"fujifilm holdings",
"regions financial corp.",
"ross stores",
"shiseido",
"fleetcor technologies inc",
"electronic arts",
"raytheon co.",
"matsui securities",
"exxonmobil",
"shionogi",
"united continental holdings",
"evergy",
"airbnb",
"caterpillar inc.",
"edison int'l",
"travelers",
"universal health services, inc.",
"aozora bank",
"tokai carbon",
"under armour class a",
"prudential financial",
"duke energy",
"cerner",
"darden restaurants",
"general mills",
"kobe steel",
"nektar therapeutics",
"meiji holdings",
"at&t inc.",
"yahoo japan",
"edreams odigeo",
"toho zinc",
"news corp. class a",
"yokohama rubber",
"japan post holdings",
"entergy corp.",
"digital realty trust inc",
"bridgestone",
"yum! brands inc",
"verisign inc.",
"denso",
"air products & chemicals inc",
"salesforce.com",
"asahi glass",
"asos.com",
"dover corp.",
"allegion",
"chevron corp.",
"rollins inc.",
"kansas city southern",
"hartford financial svc.gp.",
"western digital",
"allstate corp",
"pioneer",
"oji paper",
"amada co. ltd. ",
"nippon suisan kaisha",
"ametek inc.",
"nippon meat packers",
"toray industries",
"hess corporation",
"citizen holdings",
"pnc financial services",
"dte energy co.",
"total system services",
"merck & co.",
"ntn",
"waste management inc.",
"sumitomo electric industries",
"mazda motor",
"kao corp.",
"sumitomo heavy industries",
"marriott int'l.",
"cognizant technology solutions",
"tdk",
"ppg industries",
"cms energy",
"netapp",
"spotify",
"apartment investment & management ",
"booking holdings inc",
"fujikura",
"equinix",
"vertex pharmaceuticals inc",
"sumitomo metal mining",
"c. h. robinson worldwide",
"yandex",
"everest re group ltd.",
"jxtg holdings",
"coca-cola",
"linde plc",
"home depot",
"macy's inc.",
"paychex inc.",
"shin-etsu chemical",
"fast retailing",
"microchip technology",
"hitachi construction machinery",
"baxter international inc.",
"leggett & platt",
"yaskawa electric corporation",
"take-two interactive",
"denki kagaku kogyo"
]