companies = [
"taiyo yuden",
"nec",
"technipfmc",
"takara holdings",
"hess",
"otsuka holdings",
"xilinx",
"electronic arts",
"sealed air",
"eog resources",
"verizon communications",
"texas instruments",
"nippon meat packers",
"seven & i holdings",
"gap",
"deere &",
"all nippon airways",
"harris",
"textron",
"conocophillips",
"fortune brands home & security",
"fidelity national information services",
"johnson controls international",
"nasdaq,",
"the home depot",
"cintas",
"nrg energy",
"dainippon screen",
"mitsubishi chemical holdings",
"mgm resorts international",
"taisei",
"people's united financial",
"sumitomo osaka cement",
"sony",
"mitsubishi motors",
"williams cos.",
"akamai technologies",
"illinois tool works",
"westrock",
"snap-on",
"kajima",
"darden restaurants",
"marriott int'l.",
"denki kagaku kogyo",
"cme",
"daiichi sankyo",
"intel",
"vulcan materials",
"secom",
"aes",
"eastman chemical",
"yokogawa electric",
"dowdupont",
"sumitomo heavy industries",
"polo ralph lauren",
"lilly (eli) &",
"west japan railway",
"canon",
"takeda pharmaceutical",
"hartford financial svc.gp.",
"hologic",
"willis towers watson",
"newell brands",
"hitachi",
"d. r. horton",
"autozone",
"goldman sachs",
"juniper networks",
"united parcel service",
"davita",
"cummins",
"isuzu motors",
"c. h. robinson worldwide",
"comerica",
"resmed",
"fukuoka financial",
"fastenal",
"hino motors",
"nikon",
"mitsubishi",
"ngk insulators",
"realty income",
"prologis",
"haseko",
"inpex",
"meiji holdings",
"mitsubishi ufj financial",
"quanta services",
"philip morris international",
"tjx companies",
"baker hughes, a ge",
"mitsubishi materials",
"packaging of america",
"altria",
"stanley black & decker",
"3m",
"wellcare",
"oji paper",
"sumitomo chemical",
"zoetis",
"advantest",
"abbott laboratories",
"nisshin seifun",
"harley-davidson",
"alexion pharmaceuticals",
"regions financial",
"intel",
"mitsui fudosan",
"sempra energy",
"verizon",
"coca-cola",
"baxter international",
"air products & chemicals",
"nektar therapeutics",
"kirin brewery",
"digital realty trust",
"republic services",
"garmin .",
"activision blizzard",
"ventas",
"wabtec",
"j. front retailing",
"raytheon",
"tokuyama",
"u.s. bancorp",
"kroger",
"tokyu land",
"expeditors",
"merck &",
"kimberly-clark",
"sumitomo mitsui trust holdings",
"maruha nichiro holdings",
"sumitomo electric industries",
"alexandria real estate equities",
"archer-daniels-midland",
"aon plc",
"tokyo electron",
"ppg industries",
"nippon light metal",
"kimco realty",
"nippon paper ,",
"ricoh",
"brighthouse financial",
"o'reilly automotive",
"pnc financial services",
"essex property trust,",
"applied materials",
"becton dickinson",
"l-3 communications holdings",
"lam research",
"seiko epson",
"regency centers",
"mizuho financial",
"dish network",
"t&d holdings",
"global payments",
"mastercard",
"mitsui mining & smelting",
"union pacific",
"jfe holdings",
"allstate",
"nvidia",
"firstenergy",
"shin-etsu chemical",
"parker-hannifin",
"tapestry,",
"cms energy",
"take-two interactive",
"kyocera",
"duke realty",
"paccar",
"danaher",
"alps electric",
"ball",
"ametek",
"varian medical systems",
"trend micro",
"amphenol",
"japan post holdings",
"news class b",
"costco wholesale",
"american express",
"fanuc",
"royal caribbean cruises",
"nisshin steel",
"obayashi",
"the hershey",
"gilead sciences",
"dena",
"verisign",
"qorvo",
"fujikura",
"cincinnati financial",
"wells fargo",
"torchmark",
"franklin resources",
"salesforce.com",
"intuitive surgical",
"tyson foods",
"foot locker",
"tdk",
"capri holdings",
"western digital",
"bridgestone",
"ameriprise financial",
"national oilwell varco",
"mccormick &",
"fujitsu",
"citigroup",
"minebea",
"hanesbrands",
"jefferies financial",
"ajinomoto",
"news class a",
"principal financial",
"microchip technology",
"lkq",
"martin marietta materials",
"credit saison",
"rakuten",
"toray industries",
"rollins",
"shiseido",
"oki electric industry",
"advanced micro devices",
"equity residential",
"red hat",
"constellation brands",
"cimarex energy",
"fleetcor technologies",
"cabot oil & gas",
"unum",
"first republic bank",
"macerich",
"wynn resorts",
"msci",
"nsk",
"caterpillar",
"edison int'l",
"marathon petroleum",
"tokio marine holdings",
"asahi kasei",
"iqvia holdings",
"centerpoint energy",
"eaton",
"toho zinc",
"pioneer natural resources",
"charter communications",
"sumitomo realty & development",
"nextera energy",
"noble energy",
"teijin",
"apache",
"sl green realty",
"marui",
"sumitomo mitsui financial",
"copart",
"terumo",
"gs yuasa",
"alphabet class c",
"synchrony financial",
"transdigm",
"udr",
"lincoln national",
"ibm",
"walt disney",
"blackrock",
"colgate-palmolive",
"cerner",
"okuma holdings",
"henry schein",
"international paper",
"halliburton",
"laboratory of america holding",
"loews",
"chugai pharmaceutical",
"sony financial",
"american electric power",
"celgene",
"keysight technologies",
"waste management",
"hp",
"nucor",
"equinix",
"atmos energy",
"visa",
"brown-forman",
"subaru",
"chiba bank",
"jpmorgan chase &",
"exelon",
"kraft heinz",
"pvh",
"amada .",
"northrop grumman",
"united technologies",
"ihi",
"jgc",
"paychex",
"united continental holdings",
"borgwarner",
"toyobo",
"evergy",
"arconic",
"automatic data processing",
"alliant energy",
"fortinet",
"walgreens boots alliance",
"chiyoda",
"united health",
"whirlpool",
"general motors",
"ntt docomo",
"maxim integrated products",
"viacom",
"coty,",
"aozora bank",
"sumitomo metal mining",
"yamaha",
"boston properties",
"arista networks",
"molson coors brewing",
"vertex pharmaceuticals",
"furukawa electric",
"under armour class a",
"centurylink",
"concordia financial",
"campbell soup",
"hca holdings",
"expedia",
"cisco systems",
"cbs",
"boston scientific",
"lennar",
"delta air lines",
"jm smucker",
"sumitomo dainippon pharma",
"kla-tencor",
"morgan stanley",
"intl flavors & fragrances",
"tokai carbon",
"daiwa house industry",
"perrigo",
"pepsico",
"northern trust",
"moody's",
"motorola solutions",
"flir systems",
"citizens financial",
"diamondback energy",
"kikkoman",
"american tower",
"hormel foods",
"ingersoll-rand plc",
"micron technology",
"exxonmobil",
"public storage",
"ntn",
"fast retailing",
"walmart",
"zions bancorp",
"travelers",
"biogen",
"kellogg",
"softbank",
"emerson electric",
"wec energy",
"affiliated managers",
"yokohama rubber",
"asahi glass",
"komatsu",
"sompo holdings",
"nordstrom",
"fmc",
"tiffany &",
"bank of america",
"ntt data",
"yaskawa electric",
"ameren",
"konica minolta holdings",
"east japan railway",
"anadarko petroleum",
"alphabet class a",
"pacific metals",
"mid-america apartments",
"kawasaki kisen kaisha",
"shinsei bank",
"sumitomo",
"nippon steel",
"cvs health",
"oracle",
"mattel",
"equifax",
"american airlines",
"schlumberger .",
"kohl's",
"nike",
"sysco",
"target",
"ulta beauty",
"csx",
"conagra brands",
"dxc technology",
"exxon mobil",
"incyte",
"tobu railway",
"jack henry & associates",
"boeing",
"aflac",
"hcp",
"casio computer",
"eisai",
"nielsen holdings",
"advance auto parts",
"waters",
"recruit holdings",
"tosoh",
"microsoft",
"hasbro",
"m&t bank",
"zimmer biomet holdings",
"sekisui house",
"arthur j. gallagher &",
"corning",
"intuit",
"nippon telegraph and telephone",
"bristol-myers squibb",
"taiheiyo cement",
"cadence design systems",
"raymond james financial",
"ebara",
"lowe's cos.",
"twitter,",
"toyota motor",
"toho",
"asahi breweries",
"mylan n.v.",
"yum! brands",
"daiwa securities",
"itochu",
"matsui securities",
"fiserv",
"crown castle international",
"pulte homes",
"kansas city southern",
"japan tobacco",
"analog devices,",
"mitsui",
"skyworks solutions",
"western union",
"e*trade",
"autodesk",
"kao",
"osaka gas",
"l brands",
"sapporo holdings",
"freeport-mcmoran",
"state street",
"jxtg holdings",
"duke energy",
"booking holdings",
"norfolk southern",
"suntrust banks",
"amerisourcebergen",
"goldman sachs",
"newmont mining",
"agilent technologies",
"church & dwight",
"ebay",
"ms&ad insurance",
"microsoft",
"mettler toledo",
"nisource",
"discover financial services",
"mcdonald's",
"humana",
"omnicom",
"federal realty investment trust",
"dominion energy",
"hilton worldwide holdings",
"under armour class c",
"denso",
"align technology",
"welltower",
"tractor supply",
"mondelez international",
"carmax",
"lockheed martin",
"mitsubishi estate",
"estee lauder cos.",
"t. rowe price",
"apple",
"charles schwab",
"at&t",
"cf industries holdings",
"general dynamics",
"simon property",
"leggett & platt",
"rockwell automation",
"v.f.",
"pentair plc",
"southern",
"keio",
"avalonbay communities,",
"seagate technology",
"marathon oil",
"tokyo gas",
"monster beverage",
"alaska air",
"toppan printing",
"ppl",
"unitika",
"coca-cola",
"isetan mitsukoshi holdings",
"odakyu electric railway",
"public serv. enterprise",
"accenture plc",
"sojitz",
"tokyo tatemono",
"amgen",
"illumina",
"idexx laboratories",
"3m",
"hitachi construction machinery",
"the walt disney",
"entergy",
"jpmorgan chase",
"extra space storage",
"pinnacle west capital",
"dai-ichi life",
"takashimaya",
"dollar general",
"dowa holdings",
"caterpillar",
"kyowa hakko kirin",
"dollar tree",
"macy's",
"teleflex",
"devon energy",
"cigna",
"host hotels & resorts",
"edwards lifesciences",
"f5 networks",
"lamb weston holdings",
"ecolab",
"huntington bancshares",
"hitachi zōsen",
"kddi",
"aptiv plc",
"aeon",
"american express",
"xcel energy",
"xylem",
"cbre",
"discovery class c",
"valero energy",
"cognizant technology solutions",
"lyondellbasell",
"netapp",
"mitsubishi electric",
"gartner",
"citrix systems",
"broadcom",
"oneok",
"furukawa",
"huntington ingalls industries",
"mitsui chemicals",
"nippon kayaku",
"nissan motor",
"sky perfect jsat holdings",
"kobe steel",
"hewlett packard enterprise",
"united rentals,",
"tokyo dome",
"nichirei",
"twenty-first century fox class b",
"hollyfrontier",
"paypal",
"sumco",
"metlife",
"amazon.com",
"s&p global,",
"te connectivity .",
"progressive",
"chubb limited",
"tripadvisor",
"international business machines",
"bb&t",
"fedex",
"toyota tsusho",
"verisk analytics",
"american water works",
"adobe systems",
"mohawk industries",
"berkshire hathaway",
"a.o. smith",
"fluor",
"keycorp",
"medtronic plc",
"mitsubishi logistics",
"grainger (w.w.)",
"panasonic",
"resona holdings",
"general mills",
"the bank of new york mellon",
"ube industries",
"yamaha motor",
"abiomed",
"cardinal health",
"alliance data systems",
"shizuoka bank",
"pfizer",
"allegion",
"showa shell sekiyu",
"helmerich & payne",
"nitto denko",
"ihs markit .",
"chevron",
"synopsys",
"astellas pharma",
"carnival",
"pfizer",
"nomura holdings",
"block h&r",
"quest diagnostics",
"japan steel works",
"jtekt",
"broadridge financial solutions",
"dentsu",
"fifth third bancorp",
"mitsui o.s.k. lines",
"dai nippon printing",
"comcast",
"thermo fisher scientific",
"kinder morgan",
"shionogi",
"sherwin-williams",
"the travelers companies",
"johnson & johnson",
"ipg photonics",
"keisei electric railway",
"prudential financial",
"discovery class a",
"occidental petroleum",
"abbvie",
"apartment investment & management",
"southwest airlines",
"comsys holdings",
"centene",
"boeing",
"vornado realty trust",
"honda motor",
"fujifilm holdings",
"olympus",
"yamato holdings",
"xerox",
"avery dennison",
"central japan railway",
"qualcomm",
"apple",
"general electric",
"jacobs engineering",
"masco",
"the mosaic",
"netflix",
"tokyu",
"regeneron",
"mazda motor",
"dte energy",
"daikin industries",
"kubota",
"kawasaki heavy industries",
"suzuki motor",
"nippon suisan kaisha",
"interpublic",
"fortive",
"chevron",
"the clorox",
"ross stores",
"visa",
"procter & gamble",
"albemarle",
"everest re .",
"home depot",
"cboe global markets",
"mitsui engineering & shipbuilding",
"mitsubishi heavy industries",
"toto .",
"genuine parts",
"symantec",
"american international",
"marubeni",
"nippon electric glass",
"eversource energy",
"marsh & mclennan",
"mckesson",
"sba communications",
"showa denko",
"fuji electric holdings",
"citizen holdings",
"ansys",
"linde plc",
"celanese",
"dover",
"starbucks",
"weyerhaeuser",
"chubu electric power",
"yahoo japan",
"flowserve",
"nippon yusen",
"merck &",
"nisshinbo holdings",
"honeywell int'l",
"twenty-first century fox class a",
"universal health services,",
"consolidated edison",
"the cooper companies",
"intercontinental exchange",
"allergan, plc",
"perkinelmer",
"konami",
"stryker",
"ford motor",
"shimizu",
"assurant",
"dentsply sirona",
"anthem",
"phillips 66",
"nissan chemical industries",
"robert half international",
"best buy",
"total system services",
"nippon sheet glass",
"concho resources",
"familymart uny holdings",
"kansai electric power",
"chipotle mexican grill",
"iron mountain incorporated",
"tokyo electric power",
"norwegian cruise line",
"nippon express",
"mcdonald's",
"unitedhealth",
"pioneer",
"kuraray",
"capital one financial",
"svb financial",
"toyo seikan kaisha",
"j. b. hunt transport services",
"roper technologies",
"invesco .",
"facebook,"
]