companies = [
"ajinomoto",
"asahi breweries",
"japan tobacco",
"kikkoman",
"kirin brewery",
"meiji holdings",
"nichirei",
"nippon meat packers",
"nisshin seifun",
"sapporo holdings",
"takara holdings",
"teijin",
"toray industries",
"toyobo",
"unitika",
"nippon paper ,",
"oji paper",
"asahi kasei",
"denki kagaku kogyo",
"fujifilm holdings",
"kao",
"kuraray",
"mitsubishi chemical holdings",
"mitsui chemicals",
"nippon kayaku",
"nissan chemical industries",
"nitto denko",
"shin-etsu chemical",
"shiseido",
"showa denko",
"sumitomo chemical",
"tokuyama",
"tosoh",
"ube industries",
"astellas pharma",
"chugai pharmaceutical",
"daiichi sankyo",
"sumitomo dainippon pharma",
"eisai",
"kyowa hakko kirin",
"otsuka holdings",
"shionogi",
"takeda pharmaceutical",
"jxtg holdings",
"showa shell sekiyu",
"bridgestone",
"yokohama rubber",
"asahi glass",
"ngk insulators",
"nippon electric glass",
"nippon sheet glass",
"sumitomo osaka cement",
"taiheiyo cement",
"tokai carbon",
"toto .",
"jfe holdings",
"kobe steel",
"nippon steel",
"nisshin steel",
"pacific metals",
"dowa holdings",
"fujikura",
"furukawa",
"furukawa electric",
"mitsubishi materials",
"mitsui mining & smelting",
"nippon light metal",
"sumco",
"sumitomo electric industries",
"sumitomo metal mining",
"toho zinc",
"toyo seikan kaisha",
"amada .",
"chiyoda",
"daikin industries",
"ebara",
"hitachi construction machinery",
"hitachi zōsen",
"ihi",
"japan steel works",
"jtekt",
"komatsu",
"kubota",
"mitsubishi heavy industries",
"nsk",
"ntn",
"okuma holdings",
"sumitomo heavy industries",
"advantest",
"alps electric",
"canon",
"casio computer",
"dainippon screen",
"denso",
"fanuc",
"fuji electric holdings",
"fujitsu",
"gs yuasa",
"hitachi",
"kyocera",
"panasonic",
"minebea",
"mitsubishi electric",
"nec",
"nisshinbo holdings",
"oki electric industry",
"pioneer",
"ricoh",
"seiko epson",
"sony",
"taiyo yuden",
"tdk",
"tokyo electron",
"yaskawa electric",
"yokogawa electric",
"kawasaki heavy industries",
"mitsui engineering & shipbuilding",
"hino motors",
"honda motor",
"isuzu motors",
"mazda motor",
"mitsubishi motors",
"nissan motor",
"subaru",
"suzuki motor",
"toyota motor",
"yamaha motor",
"citizen holdings",
"konica minolta holdings",
"nikon",
"olympus",
"terumo",
"dai nippon printing",
"toppan printing",
"yamaha",
"nippon suisan kaisha",
"maruha nichiro holdings",
"inpex",
"comsys holdings",
"daiwa house industry",
"haseko",
"jgc",
"kajima",
"obayashi",
"sekisui house",
"shimizu",
"taisei",
"itochu",
"marubeni",
"mitsubishi",
"mitsui",
"sojitz",
"sumitomo",
"toyota tsusho",
"aeon",
"familymart uny holdings",
"fast retailing",
"isetan mitsukoshi holdings",
"j. front retailing",
"marui",
"seven & i holdings",
"takashimaya",
"aozora bank",
"chiba bank",
"concordia financial",
"sumitomo mitsui trust holdings",
"fukuoka financial",
"mitsubishi ufj financial",
"mizuho financial",
"resona holdings",
"shinsei bank",
"shizuoka bank",
"sumitomo mitsui financial",
"daiwa securities",
"matsui securities",
"nomura holdings",
"dai-ichi life",
"ms&ad insurance",
"sompo holdings",
"sony financial",
"t&d holdings",
"tokio marine holdings",
"credit saison",
"mitsubishi estate",
"mitsui fudosan",
"sumitomo realty & development",
"tokyo tatemono",
"tokyu land",
"central japan railway",
"east japan railway",
"keio",
"keisei electric railway",
"odakyu electric railway",
"tobu railway",
"tokyu",
"west japan railway",
"nippon express",
"yamato holdings",
"kawasaki kisen kaisha",
"mitsui o.s.k. lines",
"nippon yusen",
"all nippon airways",
"mitsubishi logistics",
"kddi",
"nippon telegraph and telephone",
"ntt data",
"ntt docomo",
"sky perfect jsat holdings",
"softbank",
"chubu electric power",
"kansai electric power",
"tokyo electric power",
"osaka gas",
"tokyo gas",
"dena",
"dentsu",
"japan post holdings",
"konami",
"rakuten",
"recruit holdings",
"secom",
"tokyo dome",
"toho",
"trend micro",
"yahoo japan"
]